### ISSUE TITLE
Implement support for loading configuration from a `config.toml` file.

### ISSUE THREAD

**Issue by doziestar** [doziestar/source_watch#1]
Create a `config.toml` file in the project root directory to store database connections and log data sources.

Tasks:

- [x] Create a config.toml file with example configuration data.
- [x] Define the structure of the configuration file.
- [x] Use a TOML parsing library to read the configuration file.

Example:

```toml

[databases]
[[databases.mysql]]
name = "MySQL Database"
host = "localhost"
port = 330
username = "root"
password = "password"
database = "test"

[[databases.postgresql]]
name = "PostgreSQL Database"
host = "localhost"
port = 543
username = "postgres"
password = "password"
database = "test"

[[databases.mongodb]]
name = "MongoDB Database"
host = "localhost"
port = 270
username = "admin"
password = "password"
database = "test"

[[databases.redis]]
name = "Redis Database"
host = "localhost"
port = 637
password = "password"

[logs]
[[logs.file]]
name = "Log File"
path = "/var/log/app.log"
format = "json"
encoding = "utf-8"
interval = 1

```
