### ISSUE TITLE
Integrate the loaded configuration into the main application.

### ISSUE THREAD

**Issue by doziestar** [doziestar/source_watch#4]
Ensure that the application uses the loaded configuration to initialize database connections and log data sources.

Tasks:

- [x] Pass the configuration data to the relevant parts of the application.
- [x] Use the configuration to establish database connections and set up log monitoring.

Example Configuration File (`config.toml`)

```toml
[databases]
[[databases.mysql]]
name = "MySQL Database"
host = "localhost"
port = 3306
username = "root"
password = "password"
database = "test"

[[databases.postgresql]]
name = "PostgreSQL Database"
host = "localhost"
port = 5432
username = "postgres"
password = "password"
database = "test"

[[databases.mongodb]]
name = "MongoDB Database"
host = "localhost"
port = 27017
username = "admin"
password = "password"
database = "test"

[[databases.redis]]
name = "Redis Database"
host = "localhost"
port = 6379
password = "password"

[logs]
[[logs.file]]
name = "Log File"
path = "/var/log/app.log"
format = "json"
encoding = "utf-8"
interval = 1

```
